CREATE DATABASE WishList;
GO
 
USE WishList;
GO

CREATE TABLE Usuario (
idUsuario TINYINT PRIMARY KEY IDENTITY (1,1),
Nome VARCHAR(30) NOT NULL,
email VARCHAR (256) NOT NULL unique,
senha VARCHAR (50) NOT NULL
);
GO

CREATE TABLE Desejos (
idDesejo TINYINT PRIMARY KEY IDENTITY (1,1),
idUsuario TINYINT FOREIGN KEY REFERENCES Usuario(idUsuario),
descricao VARCHAR (256) NOT NULL ,
);
GO

DROP DATABASE WishList
GO